name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 버튼

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4

    - name: Python 설치
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 라이브러리 설치
      run: |
        pip install pyinstaller pillow pyautogui pynput

    - name: server.exe 빌드
      run: |
        pyinstaller --onefile --windowed --name "RemoteControl_Server" `
          --hidden-import=PIL `
          --hidden-import=PIL.ImageGrab `
          --hidden-import=pyautogui `
          --hidden-import=pynput `
          --hidden-import=pynput.mouse `
          --hidden-import=pynput.keyboard `
          --hidden-import=pynput.mouse._win32 `
          --hidden-import=pynput.keyboard._win32 `
          server.py

    - name: client.exe 빌드
      run: |
        pyinstaller --onefile --windowed --name "RemoteControl_Client" `
          --hidden-import=PIL `
          --hidden-import=PIL.ImageTk `
          client.py

    - name: EXE 파일 업로드 (다운로드 가능)
      uses: actions/upload-artifact@v4
      with:
        name: RemoteControl-EXE
        path: |
          dist/RemoteControl_Server.exe
          dist/RemoteControl_Client.exe
        retention-days: 30
